# Generated by Django 2.2.19 on 2023-10-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geneid', models.IntegerField(blank=True, null=True)),
                ('chromosome', models.CharField(blank=True, max_length=10, null=True)),
                ('start', models.IntegerField(blank=True, null=True)),
                ('end', models.IntegerField(blank=True, null=True)),
                ('gl_id', models.CharField(blank=True, max_length=4471, null=True)),
                ('strand', models.CharField(blank=True, max_length=1, null=True)),
                ('samples', models.CharField(blank=True, max_length=809, null=True)),
                ('cell_types', models.CharField(blank=True, max_length=5, null=True)),
                ('overlapping', models.CharField(blank=True, max_length=5, null=True)),
                ('overlapping_regulatory_element', models.CharField(blank=True, max_length=5, null=True)),
                ('overlapping_snp', models.CharField(blank=True, max_length=5, null=True)),
                ('coservation_score', models.CharField(blank=True, max_length=5, null=True)),
                ('mfe_score', models.CharField(blank=True, max_length=5, null=True)),
                ('prognostic', models.CharField(blank=True, max_length=5, null=True)),
                ('is_contains_sample', models.BooleanField()),
            ],
            options={
                'db_table': 'genes',
            },
        ),
    ]
